gitea:
  admin:
    username: gitea_admin
    password: admin
  config:
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level

service:
  http:
    type: "NodePort"

persistence:
  enabled: false
  
redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
  